### ISSUE TITLE
加入其它引擎支持

### ISSUE THREAD

**Issue by jareguo** [cocos-creator/web-extension-detect-engine#2]
先加入 egret / laya 引擎支持
然后遍历 instant games，将其中用到的其它引擎回复到该 issue，对非自研引擎，也提供支持。如果找不出是什么引擎，可以群聊求助。

**Comment by cyy641278529** [comment]
游戏 | 引擎
-----|-----
EverWing | 未知
Words With Friends  | wwf
8ball | 未知 
solitaire | 未知 
block party | PIXI + phaser
chess | PIXI + phaser
cookie crush |  Phaser (有window.PIXI但没有版本号)
pac-man |  createjs =>EaselJS/ PreloadJS/ SoundJS/ TweenJS
endless lake | PIXI
Jigsaw Puzzle |  Phaser
the Test  | PIXI
AdVenture Capitalist | Phaser
Super Bowling |  Phaser
SNAKE/Hex FRVR | 未知
BATTLESHIP | PIXI
Master Archer | 未知
Tetris/二十一點 | Phaser+PIXI
Brick Pop | 未知
Daily Sudoku | 未知 类似Snake
籃球賽:Basketball... | playcanvas
Cooking Mama: Burger Shop | Phaser
Dino Ballz/Bingo | Phaser +PIXI
Letter Master | PIXI
Dominoes: Battle! | createjs =>EaselJS/ PreloadJS/ SoundJS/ TweenJS
Jewel Academy | Phaser +PIXI
Cut The Rope 2. | 未知, 没有用引擎直接写脚本?
WhackaMon | createjs =>EaselJS/ PreloadJS/ SoundJS/ TweenJS
迷你高爾夫遊戲: Putt...  | CANNON.version + pc?
Solitaire Live | Phaser +PIXI
Bat Climb | THREE  ?  window.THREE是undifine
Galaga | createjs =>EaselJS / PreloadJS/ SoundJS/ TweenJS.
Mars Rover | 未知, 没有用引擎直接写脚本?
Jackpot Jam: Free... | PIXI.VERSION
Star Wars: Porg... |  Phaser.VERSION
SongPop Arcade  |  未知  需要邀请好友才能玩,字会被盖住
Tower Match | Phaser
2020 Connect | Phaser
Othell  | Phaser
Valerian Space Run | createjs =>EaselJS.version/PreloadJS.version/TweenJS.version 没有soundJS
Mr.AahH!!+ | 未知 没有用引擎直接写脚本?
滑雪遊戲 : Slope Slider | playconvas
Super Dash | Phaser +PIXI
Gold Rush | PIXI
Tomb Runner | THREE
Trivia Blast | 未知
FINAL FANTASY BRAVE. | Phaser +PIXI
Galatron |  未知
Gin Rummy Saloon | createjs =>EaselJS/ PreloadJS/ SoundJS/ TweenJS
TRACK & FIELD 100M |  未知
Nom Ca |  未知
Mahjong Trails Blitz | createjs =>EaselJS / PreloadJS/ SoundJS/ TweenJS
Arkanoid |  未知
Templar 2048 | 未知
Space Invaders | Phaser +PIXI
Wonder Woman |  PlayCanvas
GG Tower Defense... | 未知
Word Streak With... | 未知
Harry High Dive | 未知
Puzzle Bobble Blitz | 未知
Box Squad Paper Golf | PlayCanvas
Zoozle Blitz | 未知
Words with Friends | wwf
Zookeeper | EaselJS/ PreloadJS/ SoundJS/ TweenJS
Kaburin! Ball | PlayCanvas
Kaburin! Dodge | PlayCanvas
Wordalot Express | 未知
Smiley Cubes |  CocosEngine 
Castle Creeps: Whack | Phaser +PIXI
Shuffle Cats Mini | PlayCanvas
LUMINES Puzzle &... | phina
